steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/line-multi-agent:$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/line-multi-agent:$BUILD_ID']
  # cloud-run-service.yamlの変数を置換
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      sed -i "s/PROJECT_ID/$PROJECT_ID/g" cloud-run-service.yaml
      sed -i "s/BUILD_ID/$BUILD_ID/g" cloud-run-service.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'services'
    - 'replace'
    - 'cloud-run-service.yaml'
    - '--region=asia-northeast1'
images:
- 'gcr.io/$PROJECT_ID/line-multi-agent:$BUILD_ID'