apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: line-multi-agent
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/timeout: "300s"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      containers:
      # メインのLINE Multi-Agentアプリケーション
      - name: line-multi-agent
        image: gcr.io/PROJECT_ID/line-multi-agent:BUILD_ID
        ports:
        - containerPort: 8080
          name: http1
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "PROJECT_ID"
        - name: PYTHONPATH
          value: "/app"
        - name: NOTION_MCP_URL
          value: "http://localhost:3001/sse"
        - name: FILESYSTEM_MCP_URL
          value: "http://localhost:8000/sse"
        resources:
          limits:
            cpu: "1"
            memory: "1.5Gi"
      # Filesystem MCP Server サイドカー（supergateayでHTTPラッパー）
      - name: filesystem-mcp-server
        image: node:20-alpine
        env:
        - name: PORT
          value: "3000"
        command: ["/bin/sh"]
        args:
        - -c
        - |
          set -e
          echo "Installing Filesystem MCP Server and supergateway..."
          npm install -g @modelcontextprotocol/server-filesystem supergateway
          echo "Starting Filesystem MCP Server with supergateway on port 3000..."
          exec npx supergateway --stdio "npx @modelcontextprotocol/server-filesystem /tmp" --port 3000 --healthEndpoint /health
        resources:
          limits:
            cpu: "0.25"
            memory: "256Mi"
      # Notion MCP Server サイドカー（supergateayでHTTPラッパー）
      - name: notion-mcp-server
        image: node:20-alpine
        env:
        - name: PORT
          value: "3001"
        - name: NOTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: notion-api-key
              key: latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          set -e
          echo "Installing Notion MCP Server and supergateway..."
          npm install -g @notionhq/notion-mcp-server supergateway
          echo "Verifying NOTION_TOKEN is set..."
          if [ -z "$NOTION_TOKEN" ]; then
            echo "ERROR: NOTION_TOKEN is not set"
            exit 1
          fi
          echo "NOTION_TOKEN is set (length: ${#NOTION_TOKEN})"
          echo "Setting NOTION_API_KEY from NOTION_TOKEN for MCP server compatibility..."
          export NOTION_API_KEY="$NOTION_TOKEN"
          echo "Testing Notion MCP Server directly..."
          timeout 10s npx @notionhq/notion-mcp-server || echo "Direct test completed"
          echo "Starting Notion MCP Server with supergateway on port 3001..."
          exec npx supergateway --stdio "npx @notionhq/notion-mcp-server" --port 3001 --healthEndpoint /health
        resources:
          limits:
            cpu: "0.25"
            memory: "256Mi"
