steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/line-multi-agent:$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/line-multi-agent:$BUILD_ID']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'line-multi-agent'
    - '--image=gcr.io/$PROJECT_ID/line-multi-agent:$BUILD_ID'
    - '--region=asia-northeast1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--cpu=800m'
    - '--memory=1Gi'
    - '--port=8080'
images:
- 'gcr.io/$PROJECT_ID/line-multi-agent:$BUILD_ID'