apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: line-multi-agent
  annotations:
    # Cloud Run 固有の設定
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # タイムアウト設定
        run.googleapis.com/timeout: "300s"
        # 最大同時リクエスト数
        run.googleapis.com/cpu-throttling: "false"
    spec:
      # サービスアカウント設定（必要に応じて）
      # serviceAccountName: my-service-account
      containerConcurrency: 10
      timeoutSeconds: 300
      containers:
      - name: app
        image: gcr.io/gen-lang-client-0075173573/line-multi-agent:latest
        ports:
        - containerPort: 8080
          name: http1
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "gen-lang-client-0075173573"
        - name: PYTHONPATH
          value: "/app"
        # リソース制限をCloud Runの制約に合わせて設定
        resources:
          limits:
            cpu: 1000m     # 1.0 CPU
            memory: 2Gi    # 2GBメモリ
          requests:
            cpu: 500m      # 0.5 CPU
            memory: 1Gi    # 1GB メモリ
