apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: line-multi-agent
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/timeout: "300s"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      containers:
      # メインのLINE Multi-Agentアプリケーション
      - name: line-multi-agent
        image: gcr.io/PROJECT_ID/line-multi-agent:BUILD_ID
        ports:
        - containerPort: 8080
          name: http1
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: "gen-lang-client-0075173573"
        - name: PYTHONPATH
          value: "/app"
        - name: NOTION_MCP_URL
          value: "http://localhost:3001/sse"
        - name: FILESYSTEM_MCP_URL
          value: "http://localhost:8000/sse"
        - name: MCP_ENABLED
          value: "true"
        - name: MCP_TIMEOUT_SECONDS
          value: "30"
        - name: LINE_CHANNEL_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: line-channel-access-token
              key: latest
        - name: LINE_CHANNEL_SECRET
          valueFrom:
            secretKeyRef:
              name: line-channel-secret
              key: latest
        resources:
          limits:
            cpu: "1"
            memory: "1.5Gi"
      # Filesystem MCP Server サイドカー（supergateayでSSE対応）
      - name: filesystem-mcp-server
        image: node:20-alpine
        env:
        - name: PORT
          value: "8000"
        command: ["/bin/sh"]
        args:
        - -c
        - |
          set -e
          echo "Installing Filesystem MCP Server and ..."
          npm install -g @modelcontextprotocol/server-filesystem supergateway
          echo "Starting Filesystem MCP Server with supergateway on port 8000..."
          exec npx supergateway --stdio "npx @modelcontextprotocol/server-filesystem /tmp" --port 8000 --healthEndpoint /health
        resources:
          limits:
            cpu: "0.25"
            memory: "256Mi"
      # Notion MCP Server サイドカー（supergateayでSSE対応）
      - name: notion-mcp-server
        image: node:20-alpine
        env:
        - name: PORT
          value: "3001"
        - name: NOTION_TOKEN
          valueFrom:
            secretKeyRef:
              name: notion-api-key
              key: latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          set -e
          echo "Installing Notion MCP Server and supergateway..."
          npm install -g @notionhq/notion-mcp-server supergateway
          echo "Verifying NOTION_TOKEN is set..."
          if [ -z "$NOTION_TOKEN" ]; then
            echo "ERROR: NOTION_TOKEN is not set"
            exit 1
          fi
          echo "NOTION_TOKEN is set (length: ${#NOTION_TOKEN})"
          # トークンを整形し、OPENAPI_MCP_HEADERSを設定
          CLEAN_TOKEN=$(echo "$NOTION_TOKEN" | tr -d '\n\r' | xargs)
          echo "Setting up OPENAPI_MCP_HEADERS environment variable for MCP Server..."
          export OPENAPI_MCP_HEADERS="{\"Authorization\":\"Bearer ${CLEAN_TOKEN}\",\"Notion-Version\":\"2022-06-28\"}"
          echo "OPENAPI_MCP_HEADERS configured: $(echo $OPENAPI_MCP_HEADERS | sed 's/Bearer [^\"]*\"/Bearer ***\"/')"
          echo "Testing Notion MCP Server directly..."
          timeout 10s npx @notionhq/notion-mcp-server || echo "Direct test completed"
          echo "Starting Notion MCP Server with supergateway on port 3001..."
          exec npx supergateway --stdio "npx @notionhq/notion-mcp-server" --port 3001 --healthEndpoint /health
        resources:
          limits:
            cpu: "0.25"
            memory: "256Mi"
