version: '3'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - LINE_CHANNEL_SECRET=${LINE_CHANNEL_SECRET}
      - LINE_CHANNEL_ACCESS_TOKEN=${LINE_CHANNEL_ACCESS_TOKEN}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/